model_name: 'tabsyn'

model:
  y_cond: False

data:
  cont_scaler: 'quantile'
  cat_encoding:  # empty (None) / onehot
  drop_cont_missing: True
  standardize_data: False
  dequant_data: False

lr: 1e-3
wd: 0
d_token: 4
token:bias: True
n_head: 1
factor: 32
num_layers: 2

max_beta: 1e-2
min_beta: 1e-5
lambd: 0.7
num_sample_steps: 200

batch_size: 4096
device: 'cuda'

# train step proportion similar to original code (4000, 10000)
train_steps_vae: 9000
train_steps_diff: 21000

denoiser:
  n_layers: 5
  n_units: 805
  emb_dim: 256